services:
    extension:
        build: .
        restart: unless-stopped
        volumes:
            - .:/app
            - node_modules:/app/node_modules
        command: sleep infinity # for debugging container
volumes:
    node_modules:
